### ISSUE TITLE
[FEATURE] Add Login Button for Anonymous Users

### ISSUE THREAD

**Issue by varundhand** [Dun-sin/Whisper#444] opened 2023-10-16 12:53 UTC
### Description

Currently, anonymous users can access the profile section, but it displays a message instructing them to **create an account**.
To enhance UX, we propose to add a **'Login' button** there itself for the anonymous user, which would **redirect him to the login Kinde authentication.**

### Screenshots

**Before:**

![Screenshot 2023-10-16 at 6 21 30 PM](https://github.com/Dun-sin/Whisper/assets/110025628/e7d3e5af-8821-4043-ab48-49835e40d613)

**After:**

![Screenshot 2023-10-16 at 6 21 45 PM](https://github.com/Dun-sin/Whisper/assets/110025628/265d6164-cb64-4504-b483-a864cced82c2)

### Additional information

The login button would ease the authentication process for the anonymous user.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment] 2023-10-16 16:08
Duplicate of #331

**Closed by Dun-sin** 2023-10-16 16:08 UTC
Labels: enhancement, feature, hacktoberfest
