### ISSUE TITLE
[FEATURE] Enable users to easily switch from anonymous to email user

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#428] opened 2023-10-15 12:53 UTC
### Description

Scenario:
I was using the app on my desktop and was really enjoying the chat I was having with a buddy, then I needed to go somewhere urgently, but because I logged in anonymously, that wasn't possible. If only there was a way to easily continue the chat from my mobile device without losing the session... Aha! Email! Let me add my email. But sadly, that's not possible.

It would be really helpful to enable anonymous users to easily add their emails (whiles not loosing their current session).

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment] 2023-10-15 12:54
duplicate of #331

**Closed by Dun-sin** 2023-10-15 12:54 UTC
Labels: enhancement, feature, hacktoberfest
