### ISSUE TITLE
Fix Default Dark Mode Icon

### ISSUE THREAD

**Issue by varundhand** [Dun-sin/Whisper#438] opened 2023-10-15 22:33 UTC
### Description

In the settings tab, there is an option for **dark mode**, and by **default, the app is set to dark mode**. But apparently, the icon displays that it is set to **light mode when we start the app.**  

### Screenshots

_The app is in dark mode but settings show that it is light mode:_

https://github.com/Dun-sin/Whisper/assets/110025628/b745ae9d-969b-434c-96a9-fe97987c6ae4

### Additional information

There is an issue with the `DarkModeContext` setup and needs to be corrected for UX enhancement.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by r0ld3x** [comment] 2023-10-16 03:39
@varundhand  assign me

**Comment by Shashankpantiitbhilai** [comment] 2023-10-16 06:39
I am interested,please assign it to me!!

**Comment by Dun-sin** [comment] 2023-10-16 08:00
Duplicate of #426

**Closed** 2023-10-16 08:00 UTC
Labels: bug, hacktoberfest
