### ISSUE TITLE
[DOCS] need Constants file for socket events

### ISSUE THREAD

**Issue by MaybeSHAH** [Dun-sin/Whisper#327] opened 2023-09-29 06:13 UTC
### Description

Organizing constants in a separate file helps keep code clean and organized. It also makes it easier to find the constant you need when working on a project, as all of them are stored in one place. This is especially useful for larger projects with multiple developers, as everyone can easily access the same set of constants.

### Additional information

Defining constants in a separate file also allows for better scalability. If changes need to be made to the constants, they can be done quickly and easily without having to search through the entire codebase. Additionally, if new constants need to be added, they can simply be added to the constants file instead of having to modify existing code.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment] 2023-09-29 06:16
duplicate of #310

**Closed by Dun-sin** 2023-09-29 06:16 UTC
Labels: documentation, hacktoberfest
