### ISSUE TITLE
Separate menu icon for delete and copy, Quote reply

### ISSUE THREAD

**Issue by Kapilrohilla** [Dun-sin/Whisper#293] opened 2023-09-26 18:45 UTC
### Description

When another user sends the message, the chat consists of 2 (kebab) menu icons.
1st for delete message.
2nd for copy, Quote reply.

### Screenshots

![Wednesday-27-September-2023-12_08_54-AM-IST](https://github.com/Dun-sin/Whisper/assets/110235703/f070a138-faf6-48ac-8207-bc292e442c03)

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment] 2023-09-26 18:47
duplicate of #289, keep in mind that when you are creating an issue, always check if it already exists before

**Closed by Dun-sin** 2023-09-26 18:47 UTC
Labels: bug, hacktoberfest
