### ISSUE TITLE
[FEATURE] add functionality for the profile page

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#214] opened 2022-10-26 09:40 UTC
### Description

This issue depends on #239 

Tasks:
- [ ] this page should not be accessible to non email users (users that didn't log in with their email)
- [ ] use the existing model for user profile
- [ ] save the details of the user to the database

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by mathiasayivor** [comment] 2022-10-26 10:55
@Dun-sin can I be assigned this?

**Comment by mathiasayivor** [comment] 2022-10-26 11:18
I don't think there's really the need to create another model, since we already have a `User` model for storing email users

**Comment by ishan-siddiqui** [comment] 2023-06-30 18:04
Hi @Dun-sin ! I would like to contribute. I think we can add the following functions to the page - 

```
const isEmailUser = (user) => {
  return user.email !== null && user.email !== undefined;
};

const isProfilePageAccessible = (user) => {
  return isEmailUser(user);
};

const renderProfilePage = (user) => {
  if (!isProfilePageAccessible(user)) {
    return <div>You must be logged in with an email address to view this page.</div>;
  } else {
    return <div>Your profile page</div>;
  }
};

```

you would need to include it in your React app. You would also need to update your app's routing so that the profile page is only accessible to users who are logged in with an email address.

I'm confident that I can complete these tasks in a timely manner. I'm available to work on this project in the evenings and on weekends.

Would you be willing to assign this issue to me?

Thanks,
Ishan

**Comment by Dun-sin** [comment] 2023-06-30 19:04
> Hi @Dun-sin ! I would like to contribute. I think we can add the following functions to the page - 
> 
> ```
> const isEmailUser = (user) => {
>   return user.email !== null && user.email !== undefined;
> };
> 
> const isProfilePageAccessible = (user) => {
>   return isEmailUser(user);
> };
> 
> const renderProfilePage = (user) => {
>   if (!isProfilePageAccessible(user)) {
>     return <div>You must be logged in with an email address to view this page.</div>;
>   } else {
>     return <div>Your profile page</div>;
>   }
> };
> 
> ```
> 
> you would need to include it in your React app. You would also need to update your app's routing so that the profile page is only accessible to users who are logged in with an email address.
> 
> I'm confident that I can complete these tasks in a timely manner. I'm available to work on this project in the evenings and on weekends.
> 
> Would you be willing to assign this issue to me?
> 
> Thanks,
> Ishan

Definitely, you should check out the PR under the issue tagged in this issue, push your changes to that branch. Here's a tip only fork that branch so you don't get confused. 


thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by ishan-siddiqui** [comment] 2023-07-01 05:18
All right. Will do so. One more question - what is the numbering convention in the branches - I can see the issue is 239 byt the branch has number 210. Kindly assist me with that.
Also, since I'll start working on this, could you please assign this issue to me?
Thanking you,
Ishan

**Comment by Dun-sin** [comment] 2023-07-01 07:35
> All right. Will do so. One more question - what is the numbering convention in the branches - I can see the issue is 239 byt the branch has number 210. Kindly assist me with that. Also, since I'll start working on this, could you please assign this issue to me? Thanking you, Ishan

Sorry, I forgot to assign you, my bad. To answer your question on the branch, it doesn't actually have a naming convention, what happened was Github automatically created it because I needed a new branch to be linked to the first issue. So github just automatically created it like [#issue_number]-[issue_name]. I hope that explains it. Good luck

**Comment by ishan-siddiqui** [comment] 2023-07-05 11:28
Hi! I am having difficulty running the application on my local machine. It seems that vite is not mentioned in the package.json file. Is there anyway we can run this on our local machine?

Will attach screenshot along with code snippets for reference.

<img width="1440" alt="Screenshot 2023-07-05 at 4 55 14 PM" src="https://github.com/Dun-sin/Whisper/assets/77967215/f3baff44-6865-48b6-953a-0a3ca23c1398">

package.json - 
```
{
  "name": "whisper",
  "version": "0.0.0-development",
  "private": true,
  "workspaces": [
    "server",
    "client"
  ],
  "scripts": {
    "start:server": "npm run start --workspace=server",
    "start:client": "npm run start --workspace=client",
    "build:client": "npm run build --workspace=client",
    "lint:client": "npm run lint --workspace=client",
    "format: client": "npm run format --workspace=client",
    "start": "npm run start:server & npm run start:client",
    "semantic-release": "semantic-release --branches main"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Dun-sin/Whisper.git"
  },
  "author": "",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Dun-sin/Whisper/issues"
  },
  "homepage": "https://github.com/Dun-sin/Whisper#readme",
  "dependencies": {
    "uuid": "^9.0.0",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "commitizen": "^4.2.6",
    "cz-conventional-changelog": "^3.3.0",
    "semantic-release": "^19.0.5"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
}
```

docker-compose.yml -
```
services:
    mongo:
        image: mongo:5.0
        restart: always
        ports:
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
```

**Comment by Dun-sin** [comment] 2023-07-06 12:59
Did you follow exactly what the readme says on how to run it?

**Comment by Dun-sin** [comment] 2023-07-19 16:21
hi @ishan-siddiqui an update on this please?

**Comment by ishan-siddiqui** [comment] 2023-07-21 20:43
Hi! I have started the client. However, there is already a profile section that already exists here..

<img width="1440" alt="Screenshot 2023-07-22 at 2 11 37 AM" src="https://github.com/Dun-sin/Whisper/assets/77967215/b0d2fefc-04ed-4404-889f-d93c2641d70c">

I can also see that the basic chat feature is missing from this branch. Hope that does not cause any inconvenience when creating a PR.
<img width="1440" alt="Screenshot 2023-07-22 at 2 13 13 AM" src="https://github.com/Dun-sin/Whisper/assets/77967215/994e5c1e-4fd4-4ee4-bc88-0201a7fc6c92">

**Comment by Dun-sin** [comment] 2023-07-22 06:22
> Hi! I have started the client. However, there is already a profile section that already exists here..
> 
> <img width="1440" alt="Screenshot 2023-07-22 at 2 11 37 AM" src="https://github.com/Dun-sin/Whisper/assets/77967215/b0d2fefc-04ed-4404-889f-d93c2641d70c">
> 
> I can also see that the basic chat feature is missing from this branch. Hope that does not cause any inconvenience when creating a PR.
> <img width="1440" alt="Screenshot 2023-07-22 at 2 13 13 AM" src="https://github.com/Dun-sin/Whisper/assets/77967215/994e5c1e-4fd4-4ee4-bc88-0201a7fc6c92">
> 

Did you actually read the issue tasks? Yes this already exists for the frontend but not the backend, this issue is to add the functionality for the backend. The chat feature doesn't exist anywhere so don't worry it's not actually the basic feature.

**Comment by ishan-siddiqui** [comment] 2023-07-23 10:46
Hi! I'm making progress on the profile page feature. I've implemented the following so far:

1. I've added functionality to the backend to prevent non-email users from accessing the profile page.
server/index.js
```
/*
  @method: get
  @end-point: /user/find
*/
app.get('/user/find', (req, res) => {
  if (!req.user) {
    res.status(401).send('Unauthorized');
    return;
  }
  User.find(req.query, (err, data) => {
    if (err) {
      console.log(err);
    } else {
      if (data.length === 0) {
        res.sendStatus(202);
      } else {
        const user = {};

        user['id'] = data[0]._id.toString();
        user['email'] = data[0].email.toString();
        res.status(200).send(JSON.stringify(user));
      }
    }
  });
});
```

2. I've added the following fields to the UserSchema model: gender, age, and aboutMe
```
// user schema 
const UserSchema = new mongoose.Schema({
	email: {
		type: String,
		required: true,
	},
	gender: {
		type: String,
		required: false,
	  },
	  age: {
		type: Number,
		required: false,
	  },
	  aboutMe: {
		type: String,
		required: false,
	  },
});
```
3. I'm still working on the functionality to save the user's profile information to the database. I'm proposing that we add a "Save Changes" button to the profile page that will take the user's input and update the MongoDB document by comparing the email address.

I'll keep you updated on my progress.

**Comment by Dun-sin** [comment] 2023-07-23 17:43
@ishan-siddiqui looking good so far, thanks for the update, and the save changes button idea sounds great, will create an issue on it

**Comment by Dun-sin** [comment] 2023-07-30 15:09
@ishan-siddiqui an update?

**Comment by ishan-siddiqui** [comment] 2023-07-31 13:48
Hi @Dun-sin,

I have added the following functionality to the backend:

1. A new endpoint, /updateProfile/:id, that allows users to update their profile information.
2. A new function in server/index.js that handles the update request.

The new endpoint takes the user's ID and the new values for their gender, age, and about me as input. The function in server/index.js checks if the user exists, and if so, updates the user's profile information in the database.

I am unable to add a button for the update functionality, as I am having trouble using React on my machine. I would be happy to provide more details about the functionality if needed.

PFA code for reference - 
server/index.js
```
/*
  This function will trigger when the user updates their profile information
  @method: put
  @end-point: /updateProfile/:id
*/
app.put('/updateProfile/:id', async (req, res) => {
  try {
    const userId = req.params.id;
    const { gender, age, aboutMe } = req.body;

    // Check if the user exists
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ message: 'User not found' });
    }

    // Update the user profile fields if provided
    if (gender) {
      user.gender = gender;
    }
    if (age) {
      user.age = age;
    }
    if (aboutMe) {
      user.aboutMe = aboutMe;
    }

    // Save the updated user document
    await user.save();

    return res.status(200).json({ message: 'Profile updated successfully', user });
  } catch (err) {
    return res.status(500).json({ message: 'Internal server error', error: err });
  }
});
```

**Comment by Dun-sin** [comment] 2023-07-31 14:33
> Hi @Dun-sin,
> 
> I have added the following functionality to the backend:
> 
> 1. A new endpoint, /updateProfile/:id, that allows users to update their profile information.
> 2. A new function in server/index.js that handles the update request.
> 
> The new endpoint takes the user's ID and the new values for their gender, age, and about me as input. The function in server/index.js checks if the user exists, and if so, updates the user's profile information in the database.
> 
> I am unable to add a button for the update functionality, as I am having trouble using React on my machine. I would be happy to provide more details about the functionality if needed.
> 
> PFA code for reference - 
> server/index.js
> ```
> /*
>   This function will trigger when the user updates their profile information
>   @method: put
>   @end-point: /updateProfile/:id
> */
> app.put('/updateProfile/:id', async (req, res) => {
>   try {
>     const userId = req.params.id;
>     const { gender, age, aboutMe } = req.body;
> 
>     // Check if the user exists
>     const user = await User.findById(userId);
>     if (!user) {
>       return res.status(404).json({ message: 'User not found' });
>     }
> 
>     // Update the user profile fields if provided
>     if (gender) {
>       user.gender = gender;
>     }
>     if (age) {
>       user.age = age;
>     }
>     if (aboutMe) {
>       user.aboutMe = aboutMe;
>     }
> 
>     // Save the updated user document
>     await user.save();
> 
>     return res.status(200).json({ message: 'Profile updated successfully', user });
>   } catch (err) {
>     return res.status(500).json({ message: 'Internal server error', error: err });
>   }
> });
> ```

So the button is already added, if you are having issues no problem just do a git pull and push your server code. I will create an issue to add the functionality in the frontend

**Comment by ishan-siddiqui** [comment] 2023-08-06 07:45
Hey @Dun-sin!
I will do git pull, However, I hope that does not discard my changes that I have made in the server file so far. Is there any way I can get the frontend code without losing my server code?
<img width="570" alt="Screenshot 2023-08-06 at 1 15 34 PM" src="https://github.com/Dun-sin/Whisper/assets/77967215/fd243705-20d0-4b95-a6a6-b660bfecec72">

**Comment by Dun-sin** [comment] 2023-08-06 08:30
> Hey @Dun-sin!
> I will do git pull, However, I hope that does not discard my changes that I have made in the server file so far. Is there any way I can get the frontend code without losing my server code?
> <img width="570" alt="Screenshot 2023-08-06 at 1 15 34 PM" src="https://github.com/Dun-sin/Whisper/assets/77967215/fd243705-20d0-4b95-a6a6-b660bfecec72">
> 

No it won't discard your code, it will just merge it that's all. As long as you don't click on the discard button, it's all fine. Don't worry

**Comment by Dun-sin** [comment] 2023-08-06 08:30
And if it does, you still have the code on your computer I assume? But naturally it shouldn't

**Comment by ishan-siddiqui** [comment] 2023-08-06 14:35
@Dun-sin I have done git pull and also have the front-end button. I will be making my PR with the backend functionality. Let me know if you would like me to add anything else.

**Comment by Dun-sin** [comment] 2023-08-06 14:44
> @Dun-sin I have done git pull and also have the front-end button. I will be making my PR with the backend functionality. Let me know if you would like me to add anything else.

Awesome, for now I got nothing🔥

**Comment by ishan-siddiqui** [comment] 2023-08-06 14:46
Great, thank you. Creating my PR now.

**Closed** 2023-08-22 09:21 UTC
Labels: enhancement, feature, 🟨 priority: medium, Medium, assigned
