### ISSUE TITLE
prettier config file missing

### ISSUE THREAD

**Issue by Shubhamsahu19** [Dun-sin/Whisper#181] opened 2022-10-20 14:53 UTC
### What would you like to share?

everyone uses prettier code formatter , so everyone has different global prettier configuration, which leads to multiple unnecessary changes in file. So having a local `prettierrc` and `prettierignore` can eliminate these unnecessary changes.

**Comment by Dun-sin** [comment] 2022-10-20 14:53
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment] 2022-10-20 17:14
You mean this? 

![IMG_20221020_181325.jpg](https://user-images.githubusercontent.com/78784850/197014961-aad34249-f5b9-46cd-b3a1-e1bc5817283a.jpg)

**Comment by mathiasayivor** [comment] 2022-10-20 19:14
I think this is a duplicate of #175

**Closed as completed** 2022-10-21 15:04 UTC
